# .golangci.yml
version: "2"  # Must be a string, not a number

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - gocritic
    - bodyclose
    - goconst
    - gocyclo
    - misspell
    - prealloc
    - whitespace


issues:
  max-same-issues: 50
  max-issues-per-linter: 50
